/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SendWhoRouteImport } from './routes/send.who'
import { Route as SendSuccessRouteImport } from './routes/send.success'
import { Route as SendConfirmRouteImport } from './routes/send.confirm'
import { Route as SendAmountRouteImport } from './routes/send.amount'
import { Route as AppSendRouteImport } from './routes/app.send'
import { Route as AppReceiveRouteImport } from './routes/app.receive'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCardsRouteImport } from './routes/app.cards'
import { Route as AppBillsRouteImport } from './routes/app.bills'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SendWhoRoute = SendWhoRouteImport.update({
  id: '/send/who',
  path: '/send/who',
  getParentRoute: () => rootRouteImport,
} as any)
const SendSuccessRoute = SendSuccessRouteImport.update({
  id: '/send/success',
  path: '/send/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SendConfirmRoute = SendConfirmRouteImport.update({
  id: '/send/confirm',
  path: '/send/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SendAmountRoute = SendAmountRouteImport.update({
  id: '/send/amount',
  path: '/send/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/balance': typeof BalanceRoute
  '/bills': typeof BillsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/cards': typeof AppCardsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/send': typeof AppSendRoute
  '/send/amount': typeof SendAmountRoute
  '/send/confirm': typeof SendConfirmRoute
  '/send/success': typeof SendSuccessRoute
  '/send/who': typeof SendWhoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/bills': typeof BillsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/cards': typeof AppCardsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/send': typeof AppSendRoute
  '/send/amount': typeof SendAmountRoute
  '/send/confirm': typeof SendConfirmRoute
  '/send/success': typeof SendSuccessRoute
  '/send/who': typeof SendWhoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/balance': typeof BalanceRoute
  '/bills': typeof BillsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/cards': typeof AppCardsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/send': typeof AppSendRoute
  '/send/amount': typeof SendAmountRoute
  '/send/confirm': typeof SendConfirmRoute
  '/send/success': typeof SendSuccessRoute
  '/send/who': typeof SendWhoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/balance'
    | '/bills'
    | '/help'
    | '/home'
    | '/settings'
    | '/app/bills'
    | '/app/cards'
    | '/app/history'
    | '/app/profile'
    | '/app/receive'
    | '/app/send'
    | '/send/amount'
    | '/send/confirm'
    | '/send/success'
    | '/send/who'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/bills'
    | '/help'
    | '/home'
    | '/settings'
    | '/app/bills'
    | '/app/cards'
    | '/app/history'
    | '/app/profile'
    | '/app/receive'
    | '/app/send'
    | '/send/amount'
    | '/send/confirm'
    | '/send/success'
    | '/send/who'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/balance'
    | '/bills'
    | '/help'
    | '/home'
    | '/settings'
    | '/app/bills'
    | '/app/cards'
    | '/app/history'
    | '/app/profile'
    | '/app/receive'
    | '/app/send'
    | '/send/amount'
    | '/send/confirm'
    | '/send/success'
    | '/send/who'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BalanceRoute: typeof BalanceRoute
  BillsRoute: typeof BillsRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  SettingsRoute: typeof SettingsRoute
  SendAmountRoute: typeof SendAmountRoute
  SendConfirmRoute: typeof SendConfirmRoute
  SendSuccessRoute: typeof SendSuccessRoute
  SendWhoRoute: typeof SendWhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/send/who': {
      id: '/send/who'
      path: '/send/who'
      fullPath: '/send/who'
      preLoaderRoute: typeof SendWhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/success': {
      id: '/send/success'
      path: '/send/success'
      fullPath: '/send/success'
      preLoaderRoute: typeof SendSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/confirm': {
      id: '/send/confirm'
      path: '/send/confirm'
      fullPath: '/send/confirm'
      preLoaderRoute: typeof SendConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/amount': {
      id: '/send/amount'
      path: '/send/amount'
      fullPath: '/send/amount'
      preLoaderRoute: typeof SendAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receive': {
      id: '/app/receive'
      path: '/receive'
      fullPath: '/app/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards': {
      id: '/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppCardsRoute: typeof AppCardsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppSendRoute: typeof AppSendRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppCardsRoute: AppCardsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppSendRoute: AppSendRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BalanceRoute: BalanceRoute,
  BillsRoute: BillsRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  SettingsRoute: SettingsRoute,
  SendAmountRoute: SendAmountRoute,
  SendConfirmRoute: SendConfirmRoute,
  SendSuccessRoute: SendSuccessRoute,
  SendWhoRoute: SendWhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
